

server:
    application:
      name: api-gateway
    port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: http://inventory-service:8084
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**



